### ISSUE TITLE
for loop over dictionary values in jinja2 templates

### ISSUE THREAD

**Issue by jaustinford** [jaustinford/ansible-es-labs#16]
This refactor will ultimately apply for [sshd_config](https://github.com/jaustinford/ansible-es-labs/blob/master/es/roles/centos/templates/etc/ssh/sshd_config) file to iterate over `es_labs_users` dictionary.

But here's a short example of the problem,

if we run `test.playbook.yml`:
```
-    hosts: localhost
     gather_facts: false

     vars:
         users:

             hsolo:
                full_name: Han Solo
                is_jedi: 'no'

             lskywalker:
                 full_name: Luke Skywalker
                 is_jedi: 'yes'

     tasks:
     -    name: copy template
          template:
              src: ./test.template.yml
              dest: ./test.result.yml

```
with template `test.template.yml` where lines 3 and 4 are missing the correct variable syntax:
```
1 {% for user in users %}
2     User name: '{{ user }}'
3     Full Name: ''
4     Is Jedi: ''
5
6 {% endfor %}
```

And I want the result in `test.result.yml` to be:
```
    User name: hsolo
    Full Name: Han Solo
    Is Jedi: 'no'

    User name: lskywalker
    Full Name: Luke Skywalker
    Is Jedi: 'yes'
```
